name: CI

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main]
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            type: linux
          - os: macos-latest
            type: macos
          - os: windows-latest
            type: windows
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      - name: Install X11 - Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install libx11-dev libxtst-dev -y
      - name: Build
        run: go build -v -o ${{ matrix.type }}/
      - name: Archive Binaries - Unix
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        run: |
          mv LICENSE README.md ${{ matrix.type }}
          tar czvf remy-${{ github.ref_name }}-${{ matrix.type }}.tar.gz ${{ matrix.type }}
      - name: Archive Binaries - Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          move LICENSE ${{ matrix.type }}
          move README.md ${{ matrix.type }}
          tar -czvf remy-${{ github.ref_name }}-${{ matrix.type }}.tar.gz ${{ matrix.type }}
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: remy-*.tar.gz
